#Numpy

In [1]:
import numpy as np

## What is [Numpy]( https://en.wikipedia.org/wiki/NumPy )?

- A Python library written in Python and C
- Used for arrays and matrices
- More effecient than lists because every element is the **same data type**
- Some math functions - trig functions, random numbers, Boolean logic, etc.
- The basis for other data science libraries like Pandas


## Creating arrays

In [2]:
# Create an array using a list
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
arr = np.array([1,2,3,4,5])
type(arr)

numpy.ndarray

In [4]:
# Create an array using range()
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Your Turn
Create a numpy array of the numbers 1 - 8 using:
1. A list
2. The `range()` function

In [5]:
# Solution
np.array([1, 2, 3, 4, 5, 6, 7, 8])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
# Solution
np.array(range(1,9))

array([1, 2, 3, 4, 5, 6, 7, 8])

## Create Special Types of Arrays

In [7]:
# Create an array of zeros
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
# Create an array of ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones(5)*7

array([7., 7., 7., 7., 7.])

In [10]:
# Create an array (of length 10) full of 7's
np.full(10, 7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [11]:
np.full(10, 1.0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
# Create an array from 0 to 29 incremented by 3s
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [13]:
# Create an array of 5 equally spaced numbers from 0 to 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Your Turn
1. Create an array of the numbers 0 to 20 incremented by 2s. Save it to a variable called `evens`. Print out `evens`.
2. Create the following array `array([0., 0.33333, 0.6666, 1.])`.

In [14]:
# Solution
evens = np.arange(0,21,2)
evens

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [15]:
# Solution
np.linspace(0,1,4)


array([0.        , 0.33333333, 0.66666667, 1.        ])

## Two Dimensional Arrays

In [16]:
# Create an array using a list of lists
np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
# Create an array using a for loop
np.array([ range(i, i+3) for i in [2,4,6]] )

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [18]:
# Create a 2-dimensional array of ones
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
# Create a 2-dimensional array filled with 7's
np.full((4,5), 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [20]:
np.ones((4,5))*7

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

### Your Turn
1. Create a 2x2 array filled with the word "HI".
2. Create the a 3x3 array with 1's in the first row, 2's in the second row, and 3's in the third row.

In [21]:
# Solution
np.full((2,2), "HI")

array([['HI', 'HI'],
       ['HI', 'HI']], dtype='<U2')

In [22]:
# Solution
np.array([[1,1,1],[2,2,2],[3,3,3]])

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [23]:
np.array([[i]* 3 for i in [1,2,3]])

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [24]:
np.array([ np.full(3,i) for i in [1, 2, 3]])

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

## Generating Random Numbers

In [25]:
# Generate 10 random numbers from 0 to 1
np.random.random(10)

array([0.77283323, 0.21302905, 0.19421523, 0.48431583, 0.21769555,
       0.1152869 , 0.47681551, 0.28105344, 0.69299236, 0.60993722])

In [26]:
# Generate 10 random numbers from a normal distribution with mean 0 and
# standard deviation of 1
np.random.normal(0,1,10)

array([ 1.28438559,  1.27530406,  0.24826775,  0.26025281, -1.0362445 ,
        0.02917239,  1.15759948,  0.25203646, -0.35546831, -0.36629816])

In [27]:
# Generate a 3x3 matrix of random numbers from a normal distribution with
# mean 0 and standard deviation 1
np.random.normal(0, 1, (3,3))

array([[ 2.52264413, -0.40342193,  0.9330644 ],
       [ 0.6675437 , -0.33934572, -2.31476772],
       [-1.1073152 , -1.72757091,  0.08532061]])

In [28]:
# Generate a 3x3 matrix of random integers from 0 to 9
np.random.randint(0, 10, (3,3))

array([[5, 0, 7],
       [7, 9, 1],
       [0, 2, 6]])

In [29]:
# Setting the seed for repeatability
np.random.seed(42)
np.random.randint(0, 10, 3)

array([6, 3, 7])

### Your Turn
Generate 10 random numbers from the **lognormal** distribution with a mean 0 and standard deviation of 1.

In [30]:
# Solution
np.random.seed(42)
np.random.lognormal(0, 1, 10)

array([1.64331272, 0.87086849, 1.91111824, 4.58609939, 0.79124045,
       0.79125344, 4.85113557, 2.15423297, 0.62533086, 1.72040554])

## dtypes

All elements of the array must be the same data type.  

In [31]:
arr = np.random.randint(0, 10, (3,3))
print(arr.dtype)
print(arr)

int64
[[4 0 9]
 [5 8 0]
 [9 2 6]]


In [32]:
arr[0,0] = 2.2
print(arr)

[[2 0 9]
 [5 8 0]
 [9 2 6]]


It will 'upcast' if needed.  
- In this example since we have one float, the integers are upcast to floats too

In [33]:
arr = np.array([1,2,3,4,5,6.2])
print(arr.dtype, arr)

float64 [1.  2.  3.  4.  5.  6.2]


We can also specify the datatype.

In [34]:
arr = np.array([1,2,3,4,5], dtype='float16')
arr.dtype

dtype('float16')

In [35]:
arr

array([1., 2., 3., 4., 5.], dtype=float16)

In [36]:
arr = np.array([1,2,3,4,5], dtype='float')
arr.dtype

dtype('float64')

### Your Turn
Create an array of the numbers 0 - 10. Save it to a variable called `my_array`. Then change the 1 in your array to be equal to 1.4. Print out `my_array`.

In [37]:
# Solution
my_array = np.arange(0,11)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
my_array[1] = 1.4
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Array Attrributes

What are attributes?
- values associated with an object
- accessed by object.attribute (like methods but without the ())
- lots of objects have attributes

In [39]:
arr1 = np.random.randint( 10, size = 9 )
arr2 = np.random.randint( 10, size = (5,7) )

print(arr1)
print(arr2)
#data type
print(arr1.dtype)
print(arr2.dtype)
#number of dimensions
print(arr1.ndim)
print(arr2.ndim)
#shape (the size of each dimension)
print(arr1.shape)
print(arr2.shape)

[3 8 2 4 2 6 4 8 6]
[[1 3 8 1 9 8 9]
 [4 1 3 6 7 2 0]
 [3 1 7 3 1 5 5]
 [9 3 5 1 9 1 9]
 [3 7 6 8 7 4 1]]
int64
int64
1
2
(9,)
(5, 7)


### Your Turn
1. What does the size attribute do?
2. Find the size of `arr1` and `arr2`.

1. Solution



In [40]:
# Solution
np.size?

In [41]:
# Solution
arr1.size

9

In [42]:
arr2.size

35

## Array Indexing

One dimensional arrays - square brackets, starting at 0 (just like lists)

In [43]:
arr = np.random.randint(10, size = 9)
print(arr)
print(arr[0])
print(arr[8])

[4 7 9 8 8 0 8 6 8]
4
8


In [44]:
arr[-1]

8

Two dimensional arrays - square brackets, starting at 0, comma-separated tuple of indices

In [45]:
arr = np.random.randint(10, size = (5,4))

print(arr)
print(arr[2,3]) #[row, column]

[[7 0 7 7]
 [2 0 7 2]
 [2 0 4 9]
 [6 9 8 6]
 [8 7 1 0]]
9


### Your Turn
1. Create an array of 11 equally spaced points from 1 to 5. Save it to a variable called `one_to_five_array`.
2. Use indexing to pull out the `3`.

In [46]:
# Solution
one_to_five_array = np.linspace( 1, 5, 11 )
one_to_five_array

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [47]:
# Solution
one_to_five_array[5]

3.0

## Slicing Arrays

Note: Default is to return views and not copies


One dimensional

In [48]:
a=5
b=a
c=5

print(a, b, c)
a=7
print(a, b, c)


5 5 5
7 5 5


In [49]:
# Using lists to demonstrate "view" and "copy" concept
a=np.array([1,2,3,4,5])
b=a
c=a.copy()
print("Before ...")
print(f"a: {a}")
print(f"b: {b}")
print(f"c: {c}")


Before ...
a: [1 2 3 4 5]
b: [1 2 3 4 5]
c: [1 2 3 4 5]


In [50]:
a[1]=8
print("After ...")
print(f"a: {a}")
print(f"b: {b}")
print(f"c: {c}")


After ...
a: [1 8 3 4 5]
b: [1 8 3 4 5]
c: [1 2 3 4 5]


In [51]:
b[3]=23
print(a)
print(b)
print(c)

[ 1  8  3 23  5]
[ 1  8  3 23  5]
[1 2 3 4 5]


In [52]:
arr = np.random.randint(10, size = 9)
print(arr)

[6 6 7 4 2 7 5 2 0]


In [53]:
# What happens if we don't copy?
arr2 = arr
arr3 = arr.copy()
print(f"arr: {arr}")
print(f"arr2: {arr2}")
print(f"arr3: {arr3}")
arr[0] = 10
print(f"arr (updated): {arr}")
print(f"arr2 (without copying): {arr2}")
print(f"arr3 (with copying): {arr3}")

arr: [6 6 7 4 2 7 5 2 0]
arr2: [6 6 7 4 2 7 5 2 0]
arr3: [6 6 7 4 2 7 5 2 0]
arr (updated): [10  6  7  4  2  7  5  2  0]
arr2 (without copying): [10  6  7  4  2  7  5  2  0]
arr3 (with copying): [6 6 7 4 2 7 5 2 0]


In [54]:
arr

array([10,  6,  7,  4,  2,  7,  5,  2,  0])

In [55]:
print(arr[:7]) #[start:stop:increment]
print(arr[4:])
print(arr[4:7])
print(arr[4:7:2])
print(arr[4:1:-1])
print(arr[-5:1:-1])

[10  6  7  4  2  7  5]
[2 7 5 2 0]
[2 7 5]
[2 5]
[2 4 7]
[2 4 7]


### Your Turn
1. Create an 10-element array full of zeros. Assign it to a variable called `zero_array`.
2. Make a copy of `zero_array` and save it as `zero_array_copy`.
3. Use slicing to pull out the first 3 elements of `zero_array_copy`.

In [56]:
# Solution
zero_array = np.zeros( 10 )
zero_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [57]:
# Solution
zero_array_copy = zero_array.copy()
zero_array_copy

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
# Solution
zero_array_copy[:3]

array([0., 0., 0.])

Two dimensional

In [59]:
arr = np.random.randint(10, size = (5,4))
print(arr, '\n')
print(arr[2:4, 0:3]) #[row, column]
print(arr)

[[2 4 2 0]
 [4 9 6 6]
 [8 9 9 2]
 [6 0 3 3]
 [4 6 6 3]] 

[[8 9 9]
 [6 0 3]]
[[2 4 2 0]
 [4 9 6 6]
 [8 9 9 2]
 [6 0 3 3]
 [4 6 6 3]]


In [60]:
arr

array([[2, 4, 2, 0],
       [4, 9, 6, 6],
       [8, 9, 9, 2],
       [6, 0, 3, 3],
       [4, 6, 6, 3]])

In [61]:
# pull first two columns of an array
print(arr[:,0:2])

[[2 4]
 [4 9]
 [8 9]
 [6 0]
 [4 6]]


In [62]:
arr[0,:]

array([2, 4, 2, 0])

### Your Turn
1. Create a 3x3 array filled with random numbers from a normal distribution with mean 0 and standard deviation 1. Save it to a variable called `normal_array`.
2. Pull out the first row of `normal_array`.

In [63]:
# Solution
normal_array = np.random.normal( 0, 1, (3, 3) )
normal_array

array([[ 0.13575383,  0.60808966,  0.70498131],
       [ 0.36092338, -1.46696789,  0.89262947],
       [-0.10525713, -0.95534644, -0.41476463]])

In [64]:
# Solution
normal_array[0]

array([0.13575383, 0.60808966, 0.70498131])

In [65]:
# Solution
normal_array[0,:]

array([0.13575383, 0.60808966, 0.70498131])

In [66]:
# Solution - not really
normal_array[0:1,:]

array([[0.13575383, 0.60808966, 0.70498131]])

In [67]:
normal_array

array([[ 0.13575383,  0.60808966,  0.70498131],
       [ 0.36092338, -1.46696789,  0.89262947],
       [-0.10525713, -0.95534644, -0.41476463]])

## Reshaping of Arrays


In [68]:
np.arange?

In [69]:
arr = np.arange(9)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [70]:
arr.shape

(9,)

In [71]:
arr = arr.reshape((3,3))
print(arr)
print(arr.reshape(9))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [72]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [74]:
np.arange(3*3*3).reshape((3,3,3)).flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Your Turn
1. Create a 3x3 array full of ones. Assign it to a variable called `ones_matrix`.
2. Flatten the array. Assign it to a variable called `ones_array`. Print out `ones_array`.

In [75]:
# Solution
ones_matrix = np.ones((3,3))
ones_matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [76]:
# Solution
ones_array = ones_matrix.flatten()
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

##Joining and Splitting Arrays

In [77]:
arr1 = np.array([[1,1,1],[2,2,2]])
arr2 = np.array([[3,3,3],[4,4,4]])
print(arr1)
print('')
print(arr2)

[[1 1 1]
 [2 2 2]]

[[3 3 3]
 [4 4 4]]


In [78]:
#default is to concatenate along the first axis (axis=0) - add rows
arr3 = np.concatenate([arr1, arr2])
print(arr3)


[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


In [79]:
#can specify to concatenate alond second axis (0 indexing) - add columns
arr4 = np.concatenate([arr1,arr2], axis=1)
print(arr4)


[[1 1 1 3 3 3]
 [2 2 2 4 4 4]]


In [80]:
arr1[:,0:2]

array([[1, 1],
       [2, 2]])

In [81]:
arr1[:,0:2].transpose()

array([[1, 2],
       [1, 2]])

In [82]:
arr1[:,2:]

array([[1],
       [2]])

In [83]:
arr2

array([[3, 3, 3],
       [4, 4, 4]])

In [84]:
np.concatenate([arr1[:,0:2].transpose(),
                arr2,
                arr1[:,2:],
                arr2],
    axis=1)

array([[1, 2, 3, 3, 3, 1, 3, 3, 3],
       [1, 2, 4, 4, 4, 2, 4, 4, 4]])

### Your Turn
1. Create a 2x2 array filled with ones. Save it as `ones_array`.
2. Create a 2x2 array filled with zeros. Save it as `zeros_array`.
3. Concatenate `ones_array` and `zeros_array` along the first axis (adding more rows).

In [85]:
# Solution
ones_array = np.ones((2,2))
ones_array

array([[1., 1.],
       [1., 1.]])

In [86]:
# Solution
zeros_array = np.zeros((2,2))
zeros_array

array([[0., 0.],
       [0., 0.]])

In [87]:
# Solution
np.concatenate([ones_array, zeros_array])

array([[1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.]])

## Ufuncs
Ufunc is a function that operates on ndarrays in an element-by-element manner.

U is for:

- Universal


In [88]:
arr = np.arange(9).reshape((3,3))
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [89]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
print(arr+5)

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [91]:
print(arr/5)

[[0.  0.2 0.4]
 [0.6 0.8 1. ]
 [1.2 1.4 1.6]]


In [92]:
print(3**arr)

[[   1    3    9]
 [  27   81  243]
 [ 729 2187 6561]]


In [93]:
print(arr**3)

[[  0   1   8]
 [ 27  64 125]
 [216 343 512]]


## Aggregate Functions

In [94]:
# Sum across all elements
print(arr)
print(np.sum(arr))  # function
print(arr.sum())   # method
print(8*(8+1)//2)  # n(n+1)/2 = sum of a seres of number from 0

[[0 1 2]
 [3 4 5]
 [6 7 8]]
36
36
36


In [95]:
# Find the minimum
np.min(arr)  # function
arr.min()    # method

0

In [96]:
# Find the maximum
np.max(arr)  # function
arr.max()    # method

8

In [97]:
# Calculate the mean
np.mean(arr)  # function
arr.mean()    # method

4.0

In [98]:
# Find the median
np.median(arr)  # function
# arr.median()    # method

4.0

In [99]:
# use a list as an argument
mylist = [1,2,3]
np.mean(mylist)

2.0

In [100]:
# arr.a

### Your Turn
1. Create a 100-element array filled with random numbers from a normal distribution with mean 10 and standard deviation 1. Save it as `random_array`.
2. Find the min, max, mean, and standard deviation of your array.

In [101]:
# Solution
np.random.seed(42)
random_array = np.random.normal( 10, 1, 100_000_000 )
random_array[:10]

array([10.49671415,  9.8617357 , 10.64768854, 11.52302986,  9.76584663,
        9.76586304, 11.57921282, 10.76743473,  9.53052561, 10.54256004])

In [102]:
# Solution
(
  random_array.min(),
  random_array.max(),
  random_array.mean(),
  random_array.std( ddof = 1 ),
  random_array.std( ddof = 0 ),
  np.std(random_array, ddof = 0 ),
)

(4.102596951413384,
 15.61194123640827,
 9.999854794500948,
 1.0000725076405985,
 1.000072502640236,
 1.000072502640236)

## Boolean Arrays

In [ ]:
np.random.seed(42)
arr = np.random.randint(10, size=(4,5))
print(arr)
print("\n")
print(arr < 3)

[[6 3 7 4 6]
 [9 2 6 7 4]
 [3 7 7 2 5]
 [4 1 7 5 1]]


[[False False False False False]
 [False  True False False False]
 [False False False  True False]
 [False  True False False  True]]


In [ ]:
# filtering
arr[arr<3]

array([2, 2, 1, 1])

In [ ]:
(arr<3)*1

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 1]])

In [ ]:
(arr<3)+0

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 1]])

In [ ]:
# count of elements that meet a condition
np.count_nonzero(arr<3)


4

In [ ]:
# count of elements that meet a condition
np.sum(arr<3)

4

In [ ]:
(arr<3).sum()

4

In [ ]:
# proportion that meets a conditions
(arr < 3).mean()


0.2

Boolean Masks - Boolean Indexing

In [ ]:
mask = (arr < 3)
print(arr)
print("")
print(mask)
print("")
arr*mask

[[6 3 7 4 6]
 [9 2 6 7 4]
 [3 7 7 2 5]
 [4 1 7 5 1]]

[[False False False False False]
 [False  True False False False]
 [False False False  True False]
 [False  True False False  True]]



array([[0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 1, 0, 0, 1]])

In [ ]:
arr*(arr < 4)

array([[0, 3, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [3, 0, 0, 2, 0],
       [0, 1, 0, 0, 1]])

For logical AND and OR, use `&` or `|` (NOT and, or)

In [ ]:
arr*((arr % 2 == 0) & (arr >= 6))

array([[6, 0, 0, 0, 6],
       [0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
mask = np.logical_and((arr % 2 == 0),(arr >= 6))
arr*mask

array([[6, 0, 0, 0, 6],
       [0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
mask = (arr % 2 == 0) | (arr >= 6)
print((arr*mask)*100)
print("")
filter = mask
print((arr[filter])*100)


[[600   0 700 400 600]
 [900 200 600 700 400]
 [  0 700 700 200   0]
 [400   0 700   0   0]]

[600 700 400 600 900 200 600 700 400 700 700 200 400 700]


In [ ]:
arr*((arr % 2 == 0) | (arr >= 6))

array([[6, 0, 7, 4, 6],
       [9, 2, 6, 7, 4],
       [0, 7, 7, 2, 0],
       [4, 0, 7, 0, 0]])

In [ ]:
mask = np.logical_or((arr % 2 == 0), (arr >= 6))
arr*mask

array([[6, 0, 7, 4, 6],
       [9, 2, 6, 7, 4],
       [0, 7, 7, 2, 0],
       [4, 0, 7, 0, 0]])

In [ ]:
# np.logical

Logical XOR

In [ ]:
arr*((arr % 2 == 0) ^ (arr >= 6))

array([[0, 0, 7, 4, 0],
       [9, 2, 0, 7, 4],
       [0, 7, 7, 2, 0],
       [4, 0, 7, 0, 0]])

In [ ]:
arr*np.logical_xor((arr % 2 == 0), (arr >= 6))

array([[0, 0, 7, 4, 0],
       [9, 2, 0, 7, 4],
       [0, 7, 7, 2, 0],
       [4, 0, 7, 0, 0]])

Logical NOT

In [ ]:
arr

array([[6, 3, 7, 4, 6],
       [9, 2, 6, 7, 4],
       [3, 7, 7, 2, 5],
       [4, 1, 7, 5, 1]])

In [ ]:
arr >= 6

array([[ True, False,  True, False,  True],
       [ True, False,  True,  True, False],
       [False,  True,  True, False, False],
       [False, False,  True, False, False]])

In [ ]:
arr*(arr >= 6)


array([[6, 0, 7, 0, 6],
       [9, 0, 6, 7, 0],
       [0, 7, 7, 0, 0],
       [0, 0, 7, 0, 0]])

In [ ]:
np.logical_not(arr >= 6)


array([[False,  True, False,  True, False],
       [False,  True, False, False,  True],
       [ True, False, False,  True,  True],
       [ True,  True, False,  True,  True]])

### Your Turn
1. Create an 20 element array with random integers from 0 to 20. Assign it to a variable called `my_array`.
2. Use boolean indexing to return the values of the array that are greater than 10.
3. Use boolean indexing to return the values of the array that are less than 3 or greater than 15.

Feel free to use either filtering, masking, or both.

In [ ]:
np.set_printoptions(linewidth=200)  # Adjust the value as needed

In [ ]:
# Solution
my_array = np.random.randint( 0, 20, (4,5) )
my_array

array([[ 0, 11, 11, 16,  9],
       [15, 14, 14, 18, 11],
       [19,  2,  4, 18,  6],
       [ 8,  6, 17,  3, 13]])

In [ ]:
# Solution
filter = my_array  > 10
filter.flatten()

array([False,  True,  True,  True, False,  True,  True,  True,  True,  True,  True, False, False,  True, False, False, False,  True, False,  True])

In [ ]:
my_array[ filter ]

array([11, 11, 16, 15, 14, 14, 18, 11, 19, 18, 17, 13])

In [ ]:
(my_array*filter ).flatten()

array([ 0, 11, 11, 16,  0, 15, 14, 14, 18, 11, 19,  0,  0, 18,  0,  0,  0, 17,  0, 13])

In [ ]:
# Solution
filter1 = my_array < 3
print(filter1.flatten())
filter2 = my_array > 15
print(filter2.flatten())
filter3 = np.logical_or( filter1, filter2)
print(filter3.flatten())

[ True False False False False False False False False False False  True False False False False False False False False]
[False False False  True False False False False  True False  True False False  True False False False  True False False]
[ True False False  True False False False False  True False  True  True False  True False False False  True False False]


In [ ]:
(my_array*filter3).flatten()

array([ 0,  0,  0, 16,  0,  0,  0,  0, 18,  0, 19,  2,  0, 18,  0,  0,  0, 17,  0,  0])

In [ ]:
my_array*filter3

array([[ 0,  0,  0, 16,  0],
       [ 0,  0,  0, 18,  0],
       [19,  2,  0, 18,  0],
       [ 0,  0, 17,  0,  0]])