# Playing with NumPY

## Setup: Import numpy

In [1]:
import numpy as np

## Problem 1: random integers



### Part 1


Create a 1 dimensional array with 10 random integers

In [2]:
import numpy as np

# Create a 1-dimensional array with 10 random integers between 0 and 100
random_array = np.random.randint(0, 100, 10)

print(random_array)


[80 31 87 45 40  9 22 52 84 13]


### Part 2


Create a second 1 dimensional array with 10 random integers.  Concatenate it with your first array to create a 2 dimensional array with shape (2,10).

**Note:**  You may have to get creative to make this work.  

In [3]:
random_array2 = np.random.randint(0, 50, 10)

print(random_array2)

[37 43 13 37  2 34 29 31 34 30]


In [4]:
concat_array = np.array((random_array, random_array2))
concat_array

array([[80, 31, 87, 45, 40,  9, 22, 52, 84, 13],
       [37, 43, 13, 37,  2, 34, 29, 31, 34, 30]])

### Part 3


Use indexing to access the first two columns in the array you created in #2.

In [5]:
concat_array[0:2:]

array([[80, 31, 87, 45, 40,  9, 22, 52, 84, 13],
       [37, 43, 13, 37,  2, 34, 29, 31, 34, 30]])

In [15]:
print(concat_array[:,0:2])

[[80 31]
 [37 43]]


## Problem 2: 2D array



Convert the array below into a 2 dimensional array


```python
arr = np.arange(70)
```

In [6]:
arr = np.arange(70)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69])

In [7]:
# find the middle value
middle = arr2d = len(arr) // 2


In [8]:
first_half = arr[:middle]
second_half = arr [middle:]

print(first_half)
print(second_half)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34]
[35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58
 59 60 61 62 63 64 65 66 67 68 69]


In [9]:
odd_numbers = arr[arr % 2 != 0]
even_numbers = arr [arr % 2 == 0]

print(odd_numbers)
print(even_numbers)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68]


In [16]:
np.reshape(arr, (10,7))

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69]])

## Problem 3: multiply


Multiply all numbers in the array below by a number of your choice.  

```python
arr = np.arange(30)
```

In [10]:
array_x = arr * 10
print(array_x)

[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170
 180 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330 340 350
 360 370 380 390 400 410 420 430 440 450 460 470 480 490 500 510 520 530
 540 550 560 570 580 590 600 610 620 630 640 650 660 670 680 690]


## Problem 4: stats


Find the min, max, and mean and standard deviation for the array below.

```python
arr = np.random.normal(5,10,10000)
```


In [11]:
mean = arr.mean()
min = arr.min()
max = arr.max()
std = arr.std()

print(mean)
print(min)
print(max)
print(std)

34.5
0
69
20.20519735117675


## Problem 5: filtering


### Part 1


Create a 4X6 array with random integers between 0 and 10.  


In [12]:
import numpy as np

# Create a 4x6 array with random integers between 0 and 10
random_array = np.random.randint(0, 11, (4, 6))

print(random_array)


[[ 7  8 10  0  7  4]
 [ 0  3  5  0  6  0]
 [ 1  1  1  5  5  4]
 [ 0  6  0  9  8  9]]


### Part 2


Create a boolean array with `True` entries where the entries in your array are greater than 6


In [13]:
random_array = np.random.randint(0, 11, (4, 6))

boolean_array = random_array > 6

print("Original array:")
print(random_array)
print("\nBoolean array (entries > 6):")
print(boolean_array)

Original array:
[[ 6  3  0  2  0  3]
 [ 9  9  7  7 10  3]
 [ 4  1  2 10  7  6]
 [ 2 10  5  9  5 10]]

Boolean array (entries > 6):
[[False False False False False False]
 [ True  True  True  True  True False]
 [False False False  True  True False]
 [False  True False  True False  True]]


### Part 3


Use your boolean array as a filter to pull out the entries greater than 6

In [14]:
filtered_array = random_array[boolean_array]

print("Original array:")
print(random_array)
print("\nBoolean array (entries > 6):")
print(boolean_array)
print("\nFiltered array (entries > 6):")
print(filtered_array)

Original array:
[[ 6  3  0  2  0  3]
 [ 9  9  7  7 10  3]
 [ 4  1  2 10  7  6]
 [ 2 10  5  9  5 10]]

Boolean array (entries > 6):
[[False False False False False False]
 [ True  True  True  True  True False]
 [False False False  True  True False]
 [False  True False  True False  True]]

Filtered array (entries > 6):
[ 9  9  7  7 10 10  7 10  9 10]
